import type { CollectionConfig } from "payload";

import { authenticatedOnly, publishedOrAdmin } from "../access.ts";
import { seoFields, slugField, statusField } from "../fields.ts";

function getSiteUrl() {
  return (process.env.NEXT_PUBLIC_SITE_URL ?? "https://help.andersen-ev.com").replace(/\/+$/, "");
}

function getArticlePath(doc: Record<string, unknown>) {
  const category = doc.category;
  const categorySlug =
    typeof category === "object" && category !== null && "slug" in category && typeof category.slug === "string" ? category.slug : "support";
  const articleSlug = typeof doc.slug === "string" ? doc.slug : "";

  return `/help-centre/articles/${categorySlug}/${articleSlug}`;
}

const reviewStatusOptions = [
  { label: "Ready", value: "ready" },
  { label: "Draft", value: "draft" },
  { label: "Needs Andersen confirmation", value: "needsConfirmation" },
] as const;

export const HelpArticles: CollectionConfig = {
  slug: "help-articles",
  access: {
    create: authenticatedOnly,
    delete: authenticatedOnly,
    read: publishedOrAdmin,
    update: authenticatedOnly,
  },
  admin: {
    components: {
      views: {
        edit: {
          visualBuilder: {
            Component: "/components/visual-builder/VisualBuilderView#VisualBuilderView",
            meta: {
              title: "Visual Builder",
            },
            path: "/visual-builder",
            tab: {
              href: ({ id, routes }) => `${routes.admin}/wysiwyg/help-articles/${id}`,
              label: "Visual Builder",
              order: 150,
            },
          },
        },
      },
    },
    defaultColumns: ["wysiwyg", "title", "category", "status", "reviewStatus", "sortOrder", "updatedAt"],
    group: "Help Centre",
    preview: (doc) => `${getSiteUrl()}${getArticlePath(doc as Record<string, unknown>)}`,
    useAsTitle: "title",
  },
  labels: {
    plural: "Help articles",
    singular: "Help article",
  },
  fields: [
    {
      name: "title",
      type: "text",
      required: true,
    },
    slugField,
    {
      name: "category",
      type: "relationship",
      admin: {
        description: "Controls which Help Centre bubble/category page this article appears under.",
      },
      relationTo: "help-categories" as unknown as "pages",
      required: true,
    },
    {
      name: "summary",
      type: "textarea",
      required: true,
    },
    {
      name: "body",
      type: "textarea",
      admin: {
        description: "Customer-facing article content. Use blank lines between paragraphs and hyphen lines for lists.",
      },
      required: true,
    },
    {
      name: "sourceUrl",
      type: "text",
      label: "Source URL",
    },
    {
      name: "reviewStatus",
      type: "select",
      admin: {
        description: "Internal editorial status. Published controls public visibility.",
      },
      defaultValue: "draft",
      label: "Review status",
      options: [...reviewStatusOptions],
      required: true,
    },
    {
      name: "sortOrder",
      type: "number",
      admin: {
        description: "Lower numbers appear first within the category.",
      },
      defaultValue: 100,
      label: "Sort order",
      required: true,
    },
    statusField,
    {
      name: "wysiwyg",
      type: "ui",
      admin: {
        components: {
          Cell: "/components/visual-builder/WysiwygCell#WysiwygCell",
          Field: "/components/visual-builder/WysiwygField#WysiwygField",
        },
        disableListColumn: false,
      },
      label: "WYSIWYG",
    },
    {
      name: "builderData",
      type: "json",
      admin: {
        description:
          "Article-specific visual layout generated by the Console WYSIWYG editor. Leave blank to use the shared Help Article Template.",
        hidden: true,
      },
      label: "Visual article layout",
    },
    seoFields,
  ],
};
